### ISSUE TITLE
Latest Flow error format not supported

### ISSUE THREAD

**Issue by 0xR** [scrooloose/syntastic#1649]
I am running the latest flowtype (0.20.1) and I get this error message on save:
`syntastic: warning: checker javascript/flow: unrecognized error format`

**Comment by 0xR** [comment]
Error messages look like this now:
```
hello-flow.js:3
  3:   return a.length;
                ^^^^^^ property `length`. Property not found in
  3:   return a.length;
              ^ Number
```

**Comment by lcd047** [comment]
The error format didn't change, in fact syntastic runs just fine after that first failure.  What happens is more stupid than that: minor bit rot in `flow`, which exposes a design problem in Vim's API.

* syntastic runs `flow status --show-all-errors --json file.js`
* `flow` starts a new server and tells you about it, but the message to `stderr` doesn't end with a newline (this is the bit rot part)
* Vim lumps together `stdout` and `stderr` from `flaw`
* as a result, syntastic can't tell where the informational message ends, and where the JSON results begin:
```
$ flow status --show-all-errors --json file.js    
Launching Flow server for /home/lcd047/tmp        
Spawned flow server (child pid=2219)              
Logs will go to /tmp/flow/zShomezSlcd047zStmp.log 
Started a new flow server: -{"passed":false, ...}
```
To work around this, either start the server before running Vim:
```
$ cd /path/to/your/project && flow start
```
-- but you need to remember to do that every time.

Or set `*_exe` (__not__ `*_exec`) to `flow check`:
```vim
let g:syntastic_syntastic_javascript_flow_exe = 'flow check'
```
-- but that will slow down all checks.

Or tell `flow` developers to end the relevant message with a newline -- but they'll probably argue that `stderr` should be read by humans, not by Vim (and they would be right).

It's outside the scope of syntastic to work around flaws in Vim. _shrug_ I'll add a note to the wiki though.

**Comment by JustinTulloss** [comment]
This is a bigger problem than just starting flow as if flow hasn't completed the check since your last save, it'll display an informational message and a progress spinner. It seems to cause the same problem.

**Comment by lcd047** [comment]
@JustinTulloss Do you have proof that this is an actual problem, or are you just speculating?  `flow` shouldn't print a progress spinner if `stderr` is not pointing to a terminal, and it isn't when `flow` is run from Vim.

**Comment by JustinTulloss** [comment]
Not just speculating, but it's the message, not the progress spinner that's the problem. From the syntastic debug log:
```
syntastic: 53.486589: checker output: ['flow is rechecking; this should not take long [processing] -{"passed":true,"errors":[],"version":"59d090c1390486bcf585e65f2cfe0214ee74f773 Dec 18 2015 16:49:22"}']
```

From looking at the flow source, it looks like that message also ends up on stderr.

**Comment by lcd047** [comment]
@JustinTulloss Does the problem go away if you do this:
```vim
let g:syntastic_syntastic_javascript_flow_exe = 'flow check'
```

**Comment by JustinTulloss** [comment]
It does (well, setting `syntastic_javascript_flow_exe` instead of `syntastic_syntastic_javascript_flow_exe` works), but it also takes 20 seconds to run the check :smiley:

**Comment by lcd047** [comment]
@JustinTulloss Well, the options are:

1. go back to `flow check`, and let people wait for `flow` to start anew every time
2. kill `stderr`, and let people puzzle it out when something breaks
3. get the problem fixed in `flow`.

The safe option is of course 1. :)

**Comment by lcd047** [comment]
Ok, commit e39f636.

**Comment by Shraymonks** [comment]
So I just ran into this issue but noticed something interesting: manually calling `:SyntasticCheck` with `syntastic__javascript_flow_exe` as `flow status` seems to work normally. (Whereas I still get `unrecognized error format` past the first write while using active mode)

What's the difference between `:SyntasticCheck` and the automatic check on write that is done during active mode? I've set up an `autocmd` to run `:SyntasticCheck` instead of using active mode and it seems to be working fine.

**Comment by lcd047** [comment]
> So I just ran into this issue but noticed something interesting: manually calling `:SyntasticCheck` with `syntastic__javascript_flow_exe` as `flow status` seems to work normally. (Whereas I still get `unrecognized error format` past the first write while using active mode)

Do you have evidence?  Please set `g:syntastic_debug` to 3, run the checker both ways, run `:mes`, and post the output.

> What's the difference between `:SyntasticCheck` and the automatic check on write that is done during active mode? I've set up an `autocmd` to run `:SyntasticCheck` instead of using active mode and it seems to be working fine.

The difference is the active mode runs the checker from syntastic's `augroup`.  Can you reproduce the problem with all other Vim plugins disabled?  Please post a debug trace for this too.

**Comment by samwgoldman** [comment]
@lcd047 Hey, I'm on the Flow team. Wondering what we can do to make this integration seamless.

If we introduced a `--quiet` option, to prevent the diagnostic output ("Launching...", etc.), would that help? Or is it really just that there's no newline between the info messages and the JSON output?

**Comment by lcd047** [comment]
@samwgoldman `flow` should be printing only errors to `stderr`, not diagnostics, if `stderr` is not a `tty`.  That's the root of the problem (that is, aside from Vim itself jumbling together `stdout` with `stderr` when running `system()`).  A `--quiet` option might be useful for other reasons, but for the purpose of syntastic, a "not a `tty`" test would be enough.

**Comment by lcd047** [comment]
This should be solved for good in bd03a27c (well, one can hope, right?).
